# Generated by Django 4.2.26 on 2025-11-10 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва категорії')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('source', models.URLField(blank=True, null=True, verbose_name='Посилання')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Зображення')),
                ('alt_text', models.TextField(blank=True, null=True, verbose_name='Альтернативний текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубліковано')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='landing.portfoliocategory', verbose_name='Категорія')),
            ],
            options={
                'verbose_name_plural': 'Роботи',
                'ordering': ['name'],
            },
        ),
    ]
