# Generated by Django 4.2.26 on 2025-11-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_alter_portfoliocategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='client',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Клієнт'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(upload_to='my_images/', verbose_name='Зображення'),
        ),
    ]
