# Generated by Django 4.2.26 on 2025-11-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_portfolioitem_client_alter_portfolioitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Короткий опис'),
        ),
    ]
