# Generated by Django 4.2.26 on 2025-11-11 20:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_portfolioitem_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='portfolio_modal_id',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Ідентифікатор модального вікна'),
            preserve_default=False,
        ),
    ]
